### ISSUE TITLE
So many tubes

### ISSUE THREAD

**Issue by LisaBosCesium** [Fordi/its-not-a-truck#8]
At around level 50, this suddenly happens, I think in the middle of already playing the level, but not sure. At any rate, has happened twice. So many tubes. 

![8E4B8A07-B43C-4F0B-B283-2F77B41EFC6B](https://user-images.githubusercontent.com/66366602/200429204-b270b266-ad8c-45cc-9a02-60d6795b9bc3.jpeg)

**Comment by Fordi** [comment]
Looks like the level got cleared out?  I'll have to see what that does, but I should modify the input such that if it doesn't parse, it just resets.

**Comment by Fordi** [comment]
Fixed.  Confirmed that emptying the level input results in the equivalent of level 200.  Now it just resets to whatever level you were already on.

**Comment by LisaBosCesium** [comment]
Ah, now I see that it’s possible to not only accidentally select the level text, which I had noticed before, but to actually delete it. It’s handy to be able to reset the level, but since I’ve accidentally had the focus in the level without intending to many, many times, maybe find a way to avoid that? I’m playing on an iPhone and the level text is often in the way of clicking to select a beaker. But I’m happy. Thanks!

![D41C741C-5981-4999-BC7A-3A91AF4FAE2A](https://user-images.githubusercontent.com/66366602/200964272-5a1de71b-d3c7-41a3-b5da-fc0e06626e06.jpeg)

**Comment by Fordi** [comment]
Hm.  I've reduced the available viewport for layout, but your screen indicates I've CSS'd wrong somewhere WRT mobile Safari.  The dark bg is supposed to cover the screen, and the tubes should be vertically centered...  looking into it.
